table Clientes
	lineageTag: c3ad52df-1e01-4eb6-91cb-6953652b28e1

	column id_cliente
		dataType: int64
		formatString: 0
		lineageTag: 75ab3073-d059-435d-817c-b81528d6b4f2
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column edad
		dataType: int64
		formatString: 0
		lineageTag: 68b41cd1-0011-47b6-9958-6b86e7da242d
		summarizeBy: sum
		sourceColumn: edad

		annotation SummarizationSetBy = Automatic

	column genero
		dataType: string
		lineageTag: a566cbb8-38ec-412e-a8e6-96d486608ebc
		summarizeBy: none
		sourceColumn: genero

		annotation SummarizationSetBy = Automatic

	column tipo_cliente
		dataType: string
		lineageTag: 9d06b715-f10e-451a-8fd3-b75dce248bdb
		summarizeBy: none
		sourceColumn: tipo_cliente

		annotation SummarizationSetBy = Automatic

	column nombre_cliente
		dataType: string
		lineageTag: f379f42b-c6e2-46ea-8df5-363a49d424e6
		summarizeBy: none
		sourceColumn: nombre_cliente

		annotation SummarizationSetBy = Automatic

	partition Clientes = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("D:\Escritorio\BI\Proyecto-final-BI\Datos_Restaurante_Ejemplo_6meses.xlsx"), null, true),
				    Clientes_Sheet = Origen{[Item="Clientes",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Clientes_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_cliente", Int64.Type}, {"edad", Int64.Type}, {"genero", type text}, {"tipo_cliente", type text}, {"nombre_cliente", type text}}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Filas en blanco eliminadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

