table Ingredientes
	lineageTag: 5879efd6-0a5f-4c11-b504-da71d9187b11

	column id_ingrediente
		dataType: int64
		formatString: 0
		lineageTag: 0e38d2ba-d4cc-45be-9f50-0206ce9048e6
		summarizeBy: none
		sourceColumn: id_ingrediente

		annotation SummarizationSetBy = Automatic

	column nombre_ingrediente
		dataType: string
		lineageTag: 368634e4-9553-494b-ace7-65ef0c0b3dfd
		summarizeBy: none
		sourceColumn: nombre_ingrediente

		annotation SummarizationSetBy = Automatic

	column unidad_medida
		dataType: string
		lineageTag: e6dd9e80-af93-47ca-8a77-0d3bdf69643f
		summarizeBy: none
		sourceColumn: unidad_medida

		annotation SummarizationSetBy = Automatic

	column costo_unitario
		dataType: double
		lineageTag: 76a3c4d4-882f-49e9-ac49-5434923ec1b1
		summarizeBy: sum
		sourceColumn: costo_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Ingredientes = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\natal_5bvjz7f\Downloads\Datos_Restaurante_Ejemplo_6meses.xlsx"), null, true),
				    Ingredientes_Sheet = Source{[Item="Ingredientes",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Ingredientes_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id_ingrediente", Int64.Type}, {"nombre_ingrediente", type text}, {"unidad_medida", type text}, {"costo_unitario", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

